#!/usr/bin/env bash
# It configures your domain zone so that the subdomain www points to
# your load-balancer IP (lb-01


display_info() {
    local domain="$1"
    local subdomain="$2"
    record_type=$(dig +short -t CNAME "$subdomain.$domain" | awk '{print "CNAME"}' || dig +short -t A "$subdomain.$domain" | awk '{print "A"}')
    destination=$(dig +short "$subdomain.$domain" | awk '{print $1}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")

for subdomain in "${subdomains[@]}"; do
    if [ "$#" -eq 2 ] && [ "$2" != "$subdomain" ]; then
        continue
    fi
    display_info "$domain" "$subdomain"
done
