#!/usr/bin/env bash
# This script Configures Nginx so that its HTTP response contains a custom
# header X-Served-By (on web-01 and web-02).

sudo apt update
sudo apt install nginx -y
grep -q "add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default ||
  sudo sed -i "/^server {/a\        add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
sudo nginx -t && sudo service nginx restart
