#!/bin/bash
# This script Configures Nginx so that its HTTP response contains a custom
# header X-Served-By (on web-01 and web-02).

sudo apt-get -y
sudo apt-get -y install nginx

sudo sed -i "42i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
