#!/usr/bin/env bash
# This script configures HAproxy so that it send traffic to web-01 and web-02

sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend main
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 54.210.106.177-web-01:80 check
    server web-02 54.174.70.150-web-02:80 check
EOF

sudo systemctl restart haproxy
sudo systemctl enable haproxy
