#!/usr/bin/env bash
# Manages 'manage_my_process'

case "$1" in
    start)
        /path/to/manage_my_process start
        ;;

    stop)
        /path/to/manage_my_process stop
        ;;

    restart)
        /path/to/manage_my_process restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
