#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration,
# displays "Hi" using a while loop and if statement.

i=0

while [ $i -lt 10 ]; do
  echo "Best School"
  if [ $i -eq 8 ]; then
    echo "Hi"
  fi
  (( i++ ))
done
