#!/usr/bin/env bash
# It displays numbers from 1 to 20 and provides custom messages for specific iterations. 

# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration
# It uses a 'while' loop and a 'case' statement to achieve this.

i=1

while [ $i -le 20 ]; do
  echo $i
  case $i in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((i++))
done
