#!/usr/bin/env bash
# Fixes this container so that Nginx is running as the nginx user.

echo "worker_processes 4;events { worker_connections 1024;}http {server {listen 8080;}}" > /tmp/conf
pkill apache2
sudo -u nginx bash -c "nginx -c /tmp/conf"
